GP/config/routes.rb
Rails.application.routes.draw do

  resources :admin_shifts
  resources :sales_admins

  resources :production_rates
  resources :material_theoreticals
  resources :theoreticalcategories
  resources :material_theoreticalcategories

  resources :lookup_prices

  resources :sold_panels
  resources :buyer_phones
  resources :buyers

  post '/shifts/startshift', to: 'shifts#startshift'
  get '/shifts/showstartshift', to: 'shifts#showstartshift'
  post '/shifts/:id/endshift', to: 'shifts#endshift'
  get '/shifts/showendshift', to: 'shifts#showendshift'
  get '/shifts/currentshift', to: 'shifts#currentshift' 
  get '/shifts/allshifts', to: 'shifts#allshifts'

  resources :categories
  get 'sessions/new'
  get "crews/get_employees"=>"crews#get_employees"
  get "crews/:id/get_employees"=>"crews#get_employees"

  
  
  resources :vendor_spares

  resources :spare_parts

  resources :shifts
  resources :production_shifts
  resources :employee_managers
  resources :employee_phones
  resources :employees

  resources :crews
  resources :vendor_containers

  resources :solar_panels
  resources :containers
  resources :machines

  resources :material_vendors
 
  resources :vendors do 
	 resources :vendor_phones
  end
  resources :material_properties

  
  resources :properties
  resources :materials
  resources :quantities

  root 'sessions#new'
  get 'login' => 'sessions#new'
  get 'report' => 'shifts#report' 
 
  post 'login' => 'sessions#create' 
  delete 'logout' => 'sessions#destroy'
  get '/crew/home' , to: 'crews#home'
  post 'delPhone' => 'vendors#pho'
  post 'production_shifts/accept' =>'production_shifts#accept'
  post 'employees/fire'=> 'employees#fire'
  post 'employees/search'=> 'employees#search' 
 
  post 'sales_admins/accept'=> 'sales_admins#accept' 
  post 'admin_shifts/accept'=> 'admin_shifts#accept'

  get 'material' => 'materials#report'

  post 'forget_password' => 'sessions#forget_password'
  get 'forget_password' => 'sessions#forget_password_form'

  post 'delPhon' => 'employees#pho'
  post 'delPhonee' => 'buyers#pho'
  post 'vendors/black' =>'vendors#black'

  post 'materialvendorcreate' => 'vendors#materialvendorcreate'
  post 'machinecreate' => 'machines#machinecreate'
  post 'notification' => 'admin_shifts#notification'
  post 'adminnotification' => 'sales_admins#adminnotification'
  
  get '*url' => 'errors#routing'

end

GP/app/models/property.rb
class Property < ActiveRecord::Base
	has_many :materialproperty
	has_many :materials, through: :materialproperty, dependent: :destroy
end

GP/app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
   skip_before_action :verify_authenticity_token
  before_action :set_property, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token
  rescue_from ActiveRecord::RecordNotFound, :with => :render_404
# Render 404 page when record not found
  def render_404      
     render :file => "/public/404.html", :status => 404,:layout => false
  end
  # GET /properties
  # GET /properties.json
  def index
    if false
      @properties = Property.all
    else
      render :file => "/public/404.html",:status  => "404"  
    end   
  end

  # GET /properties/1
  # GET /properties/1.json
  def show
    if false
    else
      render :file => "/public/404.html",:status  => "404"  
    end 
  end

  # GET /properties/new
  def new
    if false
      @property = Property.new
    else
      render :file => "/public/404.html",:status  => "404"  
    end  
  end

  # GET /properties/1/edit
  def edit
    if false
    else
      render :file => "/public/404.html",:status  => "404"  
    end  
  end

  # POST /properties
  # POST /properties.json
  def create
    @propertyname=params[:propertyname]
    @property = Property.new(name: @propertyname)
    @property.save
    render json: @property
  end

  # PATCH/PUT /properties/1
  # PATCH/PUT /properties/1.json
  def update
    respond_to do |format|
      if @property.update(property_params)
        format.html { redirect_to @property }
        format.json { render :show, status: :ok, location: @property }
      else
        format.html { render :edit }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /properties/1
  # DELETE /properties/1.json
  def destroy
    if false
      @property.destroy
      respond_to do |format|
        format.html { redirect_to properties_url }
        format.json { head :no_content }
      end
    else
      render :file => "/public/404.html",:status  => "404"  
    end   
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_property
      @property = Property.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def property_params
      params.require(:property).permit(:name)
    end
end

GP/app/helpers/properties_helper.rb
module PropertiesHelper
end

GP/app/views/properties/_form.html.erb
<%= form_for(@property) do |f| %>
  <% if @property.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@property.errors.count, "error") %> prohibited this property from being saved:</h2>

      <ul>
      <% @property.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

GP/app/views/properties/edit.html.erb
<h1>Editing Property</h1>

<%= render 'form' %>

<%= link_to 'Show', @property %> |
<%= link_to 'Back', properties_path %>

GP/app/views/properties/index.html.erb
<h1>Listing Properties</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @properties.each do |property| %>
      <tr>
        <td><%= property.name %></td>
        <td><%= link_to 'Show', property %></td>
        <td><%= link_to 'Edit', edit_property_path(property) %></td>
        <td><%= link_to 'Destroy', property, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Property', new_property_path %>

GP/app/views/properties/new.html.erb
<h1>New Property</h1>

<%= render 'form' %>

<%= link_to 'Back', properties_path %>

GP/app/views/properties/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @property.name %>
</p>

<%= link_to 'Edit', edit_property_path(@property) %> |
<%= link_to 'Back', properties_path %>