GP/config/routes.rb
Rails.application.routes.draw do

  resources :admin_shifts
  resources :sales_admins

  resources :production_rates
  resources :material_theoreticals
  resources :theoreticalcategories
  resources :material_theoreticalcategories

  resources :lookup_prices

  resources :sold_panels
  resources :buyer_phones
  resources :buyers

  post '/shifts/startshift', to: 'shifts#startshift'
  get '/shifts/showstartshift', to: 'shifts#showstartshift'
  post '/shifts/:id/endshift', to: 'shifts#endshift'
  get '/shifts/showendshift', to: 'shifts#showendshift'
  get '/shifts/currentshift', to: 'shifts#currentshift' 
  get '/shifts/allshifts', to: 'shifts#allshifts'

  resources :categories
  get 'sessions/new'
  get "crews/get_employees"=>"crews#get_employees"
  get "crews/:id/get_employees"=>"crews#get_employees"

  
  
  resources :vendor_spares

  resources :spare_parts

  resources :shifts
  resources :production_shifts
  resources :employee_managers
  resources :employee_phones
  resources :employees

  resources :crews
  resources :vendor_containers

  resources :solar_panels
  resources :containers
  resources :machines

  resources :material_vendors
 
  resources :vendors do 
	 resources :vendor_phones
  end
  resources :material_properties

  
  resources :properties
  resources :materials
  resources :quantities

  root 'sessions#new'
  get 'login' => 'sessions#new'
  get 'report' => 'shifts#report' 
 
  post 'login' => 'sessions#create' 
  delete 'logout' => 'sessions#destroy'
  get '/crew/home' , to: 'crews#home'
  post 'delPhone' => 'vendors#pho'
  post 'production_shifts/accept' =>'production_shifts#accept'
  post 'employees/fire'=> 'employees#fire'
  post 'employees/search'=> 'employees#search' 
 
  post 'sales_admins/accept'=> 'sales_admins#accept' 
  post 'admin_shifts/accept'=> 'admin_shifts#accept'

  get 'material' => 'materials#report'

  post 'forget_password' => 'sessions#forget_password'
  get 'forget_password' => 'sessions#forget_password_form'

  post 'delPhon' => 'employees#pho'
  post 'delPhonee' => 'buyers#pho'
  post 'vendors/black' =>'vendors#black'

  post 'materialvendorcreate' => 'vendors#materialvendorcreate'
  post 'machinecreate' => 'machines#machinecreate'
  post 'notification' => 'admin_shifts#notification'
  post 'adminnotification' => 'sales_admins#adminnotification'
  
  get '*url' => 'errors#routing'

end

GP/app/models/vendor_spare.rb
class VendorSpare < ActiveRecord::Base
  belongs_to :vendor 
  belongs_to :spare_part 
  
end

GP/app/controllers/vendor_spares_controller.rb
class VendorSparesController < ApplicationController
  before_action :set_vendor_spare, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token
  rescue_from ActiveRecord::RecordNotFound, :with => :render_404
# Render 404 page when record not found
  def render_404      
     render :file => "/public/404.html", :status => 404,:layout => false
  end
  # GET /vendor_spares
  # GET /vendor_spares.json
  def index
    if  false
      @vendor_spares = VendorSpare.all
    else
      render :file => "/public/404.html",:status  => "404" 
    end  
  end

  # GET /vendor_spares/1
  # GET /vendor_spares/1.json
  def show
    if  false
      else
      render :file => "/public/404.html",:status  => "404" 
    end
  end

  # GET /vendor_spares/new
  def new
    if  false
      @vendor_spare = VendorSpare.new
    else
      render :file => "/public/404.html",:status  => "404" 
    end  
  end

  # GET /vendor_spares/1/edit
  def edit
    if  false
      else
      render :file => "/public/404.html",:status  => "404" 
    end
  end

  # POST /vendor_spares
  # POST /vendor_spares.json
  def create
    @vendor_spare = VendorSpare.new(vendor_spare_params)

    respond_to do |format|
      if @vendor_spare.save
        format.html { redirect_to @vendor_spare}
        format.json { render :show, status: :created, location: @vendor_spare }
      else
        format.html { render :new }
        format.json { render json: @vendor_spare.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vendor_spares/1
  # PATCH/PUT /vendor_spares/1.json
  def update
    respond_to do |format|
      if @vendor_spare.update(vendor_spare_params)
        format.html { redirect_to @vendor_spare }
        format.json { render :show, status: :ok, location: @vendor_spare }
      else
        format.html { render :edit }
        format.json { render json: @vendor_spare.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vendor_spares/1
  # DELETE /vendor_spares/1.json
  def destroy
    if  false
      @vendor_spare.destroy
      respond_to do |format|
      format.html { redirect_to vendor_spares_url }
      format.json { head :no_content }
      end
    else
      render :file => "/public/404.html",:status  => "404" 
    end   

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vendor_spare
      @vendor_spare = VendorSpare.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vendor_spare_params
      params.require(:vendor_spare).permit(:date, :vendor_id, :spare_part_id)
    end
end

GP/app/helpers/vendor_spares_helper.rb
module VendorSparesHelper
end

GP/app/views/vendor_spares/_form.html.erb
<%= form_for(@vendor_spare) do |f| %>
  <% if @vendor_spare.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vendor_spare.errors.count, "error") %> prohibited this vendor_spare from being saved:</h2>

      <ul>
      <% @vendor_spare.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :vendor_id %><br>
    <%= f.text_field :vendor_id %>
  </div>
  <div class="field">
    <%= f.label :spare_part_id %><br>
    <%= f.text_field :spare_part_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

GP/app/views/vendor_spares/edit.html.erb
<h1>Editing Vendor Spare</h1>

<%= render 'form' %>

<%= link_to 'Show', @vendor_spare %> |
<%= link_to 'Back', vendor_spares_path %>

GP/app/views/vendor_spares/index.html.erb
<h1>Listing Vendor Spares</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Vendor</th>
      <th>Spare part</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vendor_spares.each do |vendor_spare| %>
      <tr>
        <td><%= vendor_spare.date %></td>
        <td><%= vendor_spare.vendor %></td>
        <td><%= vendor_spare.spare_part %></td>
        <td><%= link_to 'Show', vendor_spare %></td>
        <td><%= link_to 'Edit', edit_vendor_spare_path(vendor_spare) %></td>
        <td><%= link_to 'Destroy', vendor_spare, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vendor spare', new_vendor_spare_path %>

GP/app/views/vendor_spares/new.html.erb
<h1>New Vendor Spare</h1>

<%= render 'form' %>

<%= link_to 'Back', vendor_spares_path %>

GP/app/views/vendor_spares/show.html.erb
<p>
  <strong>Date:</strong>
  <%= @vendor_spare.date %>
</p>

<p>
  <strong>Vendor:</strong>
  <%= @vendor_spare.vendor %>
</p>

<p>
  <strong>Spare part:</strong>
  <%= @vendor_spare.spare_part %>
</p>

<%= link_to 'Edit', edit_vendor_spare_path(@vendor_spare) %> |
<%= link_to 'Back', vendor_spares_path %>