GP/config/routes.rb
Rails.application.routes.draw do

  resources :admin_shifts
  resources :sales_admins

  resources :production_rates
  resources :material_theoreticals
  resources :theoreticalcategories
  resources :material_theoreticalcategories

  resources :lookup_prices

  resources :sold_panels
  resources :buyer_phones
  resources :buyers

  post '/shifts/startshift', to: 'shifts#startshift'
  get '/shifts/showstartshift', to: 'shifts#showstartshift'
  post '/shifts/:id/endshift', to: 'shifts#endshift'
  get '/shifts/showendshift', to: 'shifts#showendshift'
  get '/shifts/currentshift', to: 'shifts#currentshift' 
  get '/shifts/allshifts', to: 'shifts#allshifts'

  resources :categories
  get 'sessions/new'
  get "crews/get_employees"=>"crews#get_employees"
  get "crews/:id/get_employees"=>"crews#get_employees"

  
  
  resources :vendor_spares

  resources :spare_parts

  resources :shifts
  resources :production_shifts
  resources :employee_managers
  resources :employee_phones
  resources :employees

  resources :crews
  resources :vendor_containers

  resources :solar_panels
  resources :containers
  resources :machines

  resources :material_vendors
 
  resources :vendors do 
	 resources :vendor_phones
  end
  resources :material_properties

  
  resources :properties
  resources :materials
  resources :quantities

  root 'sessions#new'
  get 'login' => 'sessions#new'
  get 'report' => 'shifts#report' 
 
  post 'login' => 'sessions#create' 
  delete 'logout' => 'sessions#destroy'
  get '/crew/home' , to: 'crews#home'
  post 'delPhone' => 'vendors#pho'
  post 'production_shifts/accept' =>'production_shifts#accept'
  post 'employees/fire'=> 'employees#fire'
  post 'employees/search'=> 'employees#search' 
 
  post 'sales_admins/accept'=> 'sales_admins#accept' 
  post 'admin_shifts/accept'=> 'admin_shifts#accept'

  get 'material' => 'materials#report'

  post 'forget_password' => 'sessions#forget_password'
  get 'forget_password' => 'sessions#forget_password_form'

  post 'delPhon' => 'employees#pho'
  post 'delPhonee' => 'buyers#pho'
  post 'vendors/black' =>'vendors#black'

  post 'materialvendorcreate' => 'vendors#materialvendorcreate'
  post 'machinecreate' => 'machines#machinecreate'
  post 'notification' => 'admin_shifts#notification'
  post 'adminnotification' => 'sales_admins#adminnotification'
  
  get '*url' => 'errors#routing'

end

GP/app/models/material_theoretical.rb
class MaterialTheoretical < ActiveRecord::Base
	belongs_to :theoreticalcategory
	belongs_to :material
end

GP/app/controllers/material_theoreticals_controller.rb
class MaterialTheoreticalsController < ApplicationController
  before_action :set_material_theoretical, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token
  rescue_from ActiveRecord::RecordNotFound, :with => :render_404
# Render 404 page when record not found
  def render_404      
     render :file => "/public/404.html", :status => 404,:layout => false
  end

  # GET /material_theoreticals
  def index
    if  false 
       @material_theoreticals = MaterialTheoretical.all
    else
      render :file => "/public/404.html",:status  => "404" 
    end  
  end

  # GET /material_theoreticals/1
  def show
    if  false
      else
      render :file => "/public/404.html",:status  => "404" 
    end
  end

  # GET /material_theoreticals/new
  def new
    if  false
       @material_theoretical = MaterialTheoretical.new
    else
      render :file => "/public/404.html",:status  => "404" 
    end  
  end

  # GET /material_theoreticals/1/edit
  def edit
    if  false
      else
      render :file => "/public/404.html",:status  => "404" 
    end
  end

  # POST /material_theoreticals
  def create
    @material_theoretical = MaterialTheoretical.new(material_theoretical_params)
    respond_to do |format|
      if @material_theoretical.save
        format.html { redirect_to @material_theoretical }
        format.json { render :show, status: :created, location: @material_theoretical }
      else
        format.html { render :new }
        format.json { render json: @material_theoretical.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /material_theoreticals/1
  # PATCH/PUT /material_theoreticals/1.json
  def update
    respond_to do |format|
      if @material_theoretical.update(material_theoretical_params)
        format.html { redirect_to @material_theoretical, notice: 'Material theoretical was successfully updated.' }
        format.json { render :show, status: :ok, location: @material_theoretical }
      else
        format.html { render :edit }
        format.json { render json: @material_theoretical.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /material_theoreticals/1
  # DELETE /material_theoreticals/1.json
  def destroy
    if false
      @material_theoretical.destroy
      respond_to do |format|
        format.html { redirect_to material_theoreticals_url, notice: 'Material theoretical was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      render :file => "/public/404.html",:status  => "404" 
    end       
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_material_theoretical
      @material_theoretical = MaterialTheoretical.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def material_theoretical_params
      params.require(:material_theoretical).permit(:value)
    end
end

GP/app/helpers/material_theoreticals_helper.rb
module MaterialTheoreticalsHelper
end

GP/app/views/material_theoreticals/_form.html.erb
<%= form_for(@material_theoretical) do |f| %>
  <% if @material_theoretical.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@material_theoretical.errors.count, "error") %> prohibited this material_theoretical from being saved:</h2>

      <ul>
      <% @material_theoretical.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :value %><br>
    <%= f.text_field :value %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

GP/app/views/material_theoreticals/edit.html.erb
<h1>Editing Material Theoretical</h1>

<%= render 'form' %>

<%= link_to 'Show', @material_theoretical %> |
<%= link_to 'Back', material_theoreticals_path %>

GP/app/views/material_theoreticals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Material Theoreticals</h1>

<table>
  <thead>
    <tr>
      <th>Value</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @material_theoreticals.each do |material_theoretical| %>
      <tr>
        <td><%= material_theoretical.value %></td>
        <td><%= link_to 'Show', material_theoretical %></td>
        <td><%= link_to 'Edit', edit_material_theoretical_path(material_theoretical) %></td>
        <td><%= link_to 'Destroy', material_theoretical, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Material theoretical', new_material_theoretical_path %>

GP/app/views/material_theoreticals/new.html.erb
<h1>New Material Theoretical</h1>

<%= render 'form' %>

<%= link_to 'Back', material_theoreticals_path %>

GP/app/views/material_theoreticals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Value:</strong>
  <%= @material_theoretical.value %>
</p>

<%= link_to 'Edit', edit_material_theoretical_path(@material_theoretical) %> |
<%= link_to 'Back', material_theoreticals_path %>