GP/config/routes.rb
Rails.application.routes.draw do

  resources :admin_shifts
  resources :sales_admins

  resources :production_rates
  resources :material_theoreticals
  resources :theoreticalcategories
  resources :material_theoreticalcategories

  resources :lookup_prices

  resources :sold_panels
  resources :buyer_phones
  resources :buyers

  post '/shifts/startshift', to: 'shifts#startshift'
  get '/shifts/showstartshift', to: 'shifts#showstartshift'
  post '/shifts/:id/endshift', to: 'shifts#endshift'
  get '/shifts/showendshift', to: 'shifts#showendshift'
  get '/shifts/currentshift', to: 'shifts#currentshift' 
  get '/shifts/allshifts', to: 'shifts#allshifts'

  resources :categories
  get 'sessions/new'
  get "crews/get_employees"=>"crews#get_employees"
  get "crews/:id/get_employees"=>"crews#get_employees"

  
  
  resources :vendor_spares

  resources :spare_parts

  resources :shifts
  resources :production_shifts
  resources :employee_managers
  resources :employee_phones
  resources :employees

  resources :crews
  resources :vendor_containers

  resources :solar_panels
  resources :containers
  resources :machines

  resources :material_vendors
 
  resources :vendors do 
	 resources :vendor_phones
  end
  resources :material_properties

  
  resources :properties
  resources :materials
  resources :quantities

  root 'sessions#new'
  get 'login' => 'sessions#new'
  get 'report' => 'shifts#report' 
 
  post 'login' => 'sessions#create' 
  delete 'logout' => 'sessions#destroy'
  get '/crew/home' , to: 'crews#home'
  post 'delPhone' => 'vendors#pho'
  post 'production_shifts/accept' =>'production_shifts#accept'
  post 'employees/fire'=> 'employees#fire'
  post 'employees/search'=> 'employees#search' 
 
  post 'sales_admins/accept'=> 'sales_admins#accept' 
  post 'admin_shifts/accept'=> 'admin_shifts#accept'

  get 'material' => 'materials#report'

  post 'forget_password' => 'sessions#forget_password'
  get 'forget_password' => 'sessions#forget_password_form'

  post 'delPhon' => 'employees#pho'
  post 'delPhonee' => 'buyers#pho'
  post 'vendors/black' =>'vendors#black'

  post 'materialvendorcreate' => 'vendors#materialvendorcreate'
  post 'machinecreate' => 'machines#machinecreate'
  post 'notification' => 'admin_shifts#notification'
  post 'adminnotification' => 'sales_admins#adminnotification'
  
  get '*url' => 'errors#routing'

end

GP/app/models/material_vendor.rb
class MaterialVendor < ActiveRecord::Base
  belongs_to :vendor
  belongs_to :material
end

GP/app/controllers/material_vendors_controller.rb
class MaterialVendorsController < ApplicationController
   skip_before_action :verify_authenticity_token
  before_action :set_material_vendor, only: [:show, :edit, :update, :destroy]
  rescue_from ActiveRecord::RecordNotFound, :with => :render_404
# Render 404 page when record not found
  def render_404      
     render :file => "/public/404.html", :status => 404,:layout => false
  end
  # GET /material_vendors
  # GET /material_vendors.json
  def index
    if false
      @material_vendors = MaterialVendor.all
    else
      render :file => "/public/404.html",:status  => "404" 
    end
  end

  # GET /material_vendors/1
  # GET /material_vendors/1.json
  def show
    if false
    else
      render :file => "/public/404.html",:status  => "404" 
    end
  end

  # GET /material_vendors/new
  def new
    if false
      @material_vendor = MaterialVendor.new
    else
      render :file => "/public/404.html",:status  => "404" 
    end  
  end

  # GET /material_vendors/1/edit
  def edit
    if false
    else
      render :file => "/public/404.html",:status  => "404" 
    end
  end

  # POST /material_vendors
  # POST /material_vendors.json
  def create
    @material_vendor = MaterialVendor.new(material_vendor_params)

    respond_to do |format|
      if @material_vendor.save
        format.html { redirect_to @material_vendor }
        format.json { render :show, status: :created, location: @material_vendor }
      else
        format.html { render :new }
        format.json { render json: @material_vendor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /material_vendors/1
  # PATCH/PUT /material_vendors/1.json
  def update
    respond_to do |format|
      if @material_vendor.update(material_vendor_params)
        format.html { redirect_to @material_vendor }
        format.json { render :show, status: :ok, location: @material_vendor }
      else
        format.html { render :edit }
        format.json { render json: @material_vendor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /material_vendors/1
  # DELETE /material_vendors/1.json
  def destroy
    if false
      @material_vendor.destroy
      respond_to do |format|
        format.html { redirect_to material_vendors_url }
        format.json { head :no_content }
      end
    else
      render :file => "/public/404.html",:status  => "404" 
    end  
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_material_vendor
      @material_vendor = MaterialVendor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def material_vendor_params
      params.require(:material_vendor).permit(:vendor_id, :material_id, :date)
    end
end

GP/app/helpers/material_vendors_helper.rb
module MaterialVendorsHelper
end

GP/app/views/material_vendors/_form.html.erb
<%= form_for(@material_vendor) do |f| %>
  <% if @material_vendor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@material_vendor.errors.count, "error") %> prohibited this material_vendor from being saved:</h2>

      <ul>
      <% @material_vendor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :vendor_id %><br>
    <%= f.text_field :vendor_id %>
  </div>
  <div class="field">
    <%= f.label :material_id %><br>
    <%= f.text_field :material_id %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

GP/app/views/material_vendors/edit.html.erb
<h1>Editing Material Vendor</h1>

<%= render 'form' %>

<%= link_to 'Show', @material_vendor %> |
<%= link_to 'Back', material_vendors_path %>

GP/app/views/material_vendors/index.html.erb
<h1>Listing Material Vendors</h1>

<table>
  <thead>
    <tr>
      <th>Vendor</th>
      <th>Material</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @material_vendors.each do |material_vendor| %>
      <tr>
        <td><%= material_vendor.vendor %></td>
        <td><%= material_vendor.material %></td>
        <td><%= material_vendor.date %></td>
        <td><%= link_to 'Show', material_vendor %></td>
        <td><%= link_to 'Edit', edit_material_vendor_path(material_vendor) %></td>
        <td><%= link_to 'Destroy', material_vendor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Material vendor', new_material_vendor_path %>

GP/app/views/material_vendors/new.html.erb
<h1>New Material Vendor</h1>

<%= render 'form' %>

<%= link_to 'Back', material_vendors_path %>

GP/app/views/material_vendors/show.html.erb
<p>
  <strong>Vendor:</strong>
  <%= @material_vendor.vendor %>
</p>

<p>
  <strong>Material:</strong>
  <%= @material_vendor.material %>
</p>

<p>
  <strong>Date:</strong>
  <%= @material_vendor.date %>
</p>

<%= link_to 'Edit', edit_material_vendor_path(@material_vendor) %> |
<%= link_to 'Back', material_vendors_path %>